### ISSUE TITLE
Resolution not found

### ISSUE THREAD

**Issue by voltz123** [CoderJoeW/AutoWizard101#1]
Hi, can you please help me with following error

System.Configuration.SettingsPropertyNotFoundException: 'The settings property 'Resolution' was not found.'

thank you

**Comment by CoderJoeW** [comment]
This should be resolved now. Congratulations by the way on resparking my interest in the project I suppose I should do some more actual work on it

**Comment by voltz123** [comment]
Hi Joey,

Thanks for taking the time to look in to this.
It now boots for me but when i click start configuration nothing happens
and it eventually goes unresponsive.
Do I need a OCR Space Api Key? if so how can I find this?

Thanks
Shane

**Comment by CoderJoeW** [comment]
@voltz123 You dont really need the OCR key. It mostly for mana estimation so you dont really need to run the confirguration.

Right now it really only has support for farming the halfang battle with the fire wizards meteor

I am working on removing the teleport requirement for exiting the dungeon which will save massively on mana

After I get that loop ironed out I will add support for all the different wizards and then I will move on to other aspects of the bot such as farming the bazaar for reagents and other things

**Comment by voltz123** [comment]
Awesome mate,

I look forward to seeing the regent buy bot. Buying regents is a bastard
these days since everyone has a bot.
I'll be keeping an eye out for your updates :)

Cheers

**Comment by CoderJoeW** [comment]
@voltz123 I released a version a few moments ago containing a reagent farming bot

Very small list of supported reagents at the moment mainly because the bazaar is very barren at the moment but I will continue to work torwards getting support for all reagents
